### ISSUE TITLE
Experimental ABIEncoderV2 support?

### ISSUE THREAD

**Issue by petarjs** [rust-ethereum/ethabi#113]
Hey guys, do you support the experimental ABIEncoderV2?

That would allow passing arrays and structs as Solidity function parameters.

Thanks!

**Comment by debris** [comment]
We do not, but PRs are welcomed 😉

**Comment by tkmct** [comment]
Is there someone working on this issue?
If not, I'd like to give it a try.

**Comment by dvdplm** [comment]
@tkmct I don’t think so, have at it! :)

**Comment by dvdplm** [comment]
@tkmct any progress on this on your end?

**Comment by vkgnosis** [comment]
Fixed on master.
