### ISSUE TITLE
Parsing constant functions from newer solidity ("stateMutability" instead of "constant")

### ISSUE THREAD

**Issue by smessmer** [rust-ethereum/ethabi#208]
In the original JSON ABI specification, there was a `constant` flag for each function, but that was deprecated and is now replaced with `stateMutability`. Newer solidity only generates `stateMutability` in the JSON output, `constant` isn't generated anymore. However, ethabi deserialization still attempts to find a `constant` parameter, and since it's missing, erroneously marks all functions as non-constant even if they have `stateMutability: "view"` set in the JSON.

**Comment by vkgnosis** [comment]
StateMutability has been added in 9121c221b9d83b7931022e47f526591801699652 .
