### ISSUE TITLE
Support error type

### ISSUE THREAD

**Issue by cburgdorf** [rust-ethereum/ethabi#225]
There doesn't seem to exist support for the new `error` type that is defined in the latest ABI spec.

Consider the followign solidity code:

```solidity
pragma solidity ^0.8.5;

error DummyError(uint256 reason);

contract Foo {

  function bar() public pure {
    revert DummyError({reason: 4});
  }
}
```

The ABI that `solc` generates from this is:

```json
[
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"reason",
            "type":"uint256"
         }
      ],
      "name":"DummyError",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"bar",
      "outputs":[
         
      ],
      "stateMutability":"pure",
      "type":"function"
   }
]
```

Feeding that to `ethabi` results in the following error:

>"Invalid operation type error."

So, I guess `error` is just not yet supported as a `type`.

**Comment by azf20** [comment]
We are also seeing this issue on graphprotocol/graph-node https://github.com/graphprotocol/graph-node/issues/2577

**Comment by gakonst** [comment]
bump @vkgnosis do you think Gnosis is able to allocate any resources on this? we're also encountering it in [Foundry](https://github.com/gakonst/foundry/)

**Comment by nlordell** [comment]
Unfortunately we don't have resources for this at the moment. Fortunately, someone has a draft PR already started here: https://github.com/rust-ethereum/ethabi/pull/251

I'll be happy to review and merge as soon it's ready.

**Comment by mattsse** [comment]
@nlordell #251 is ready now, also I forgot to follow up on #248, that is already ready now
