### ISSUE TITLE
Remove Unused Error Types

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-ethereum/ethabi#235]
Can I remove these types? So, I don't need to handle the no-std for them.

I didn't find any usage of them under the current code. 

https://github.com/rust-ethereum/ethabi/blob/09da0834d95f8b43377ca22d7b1c97a2401f4b0c/ethabi/src/errors.rs#L31-L45

**Comment by vkgnosis** [comment]
If they really aren't used then I'd say go ahead but with these `#[from] `s it could be the case that they are only used implicitly when applying `?` to a function that returns the inner error.

**Comment by AurevoirXavier** [comment]
> If they really aren't used then I'd say go ahead but with these `#[from] `s it could be the case that they are only used implicitly when applying `?` to a function that returns the inner error.

Yes, I have just found that.
