### ISSUE TITLE
Function should have a method to retrieve the 4 byte signature

### ISSUE THREAD

**Issue by ryanobjc** [rust-ethereum/ethabi#243]
Function has been written towards encoding rust types for sending transactions.  But decoding on-chain bytes given an ABI is another important use case.  

One blocker is Function cannot tell you what the 4 byte signature is.  Doing it 'yourself' is hard because the signature module is private (so one would have to re-invent that code), and the 'input_param_types()' method is also private.  

Hashing the results of 'signature' isn't sufficient since ETH smart contracts don't use the return type in the hash.

**Comment by alex88** [comment]
@ryanobjc had the same issue, you can use the master repo and you get the function
