### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by gakonst** [rust-ethereum/ethabi#252]
It'd be nice if we could cut a new release for us to support downstream in ethers-rs / foundry. Would encourage @nlordell or @vkgnosis to join either the [foundry](https://t.me/foundry) or [ethers](https://t.me/ethers_rs) chatrooms so that we can have a more direct point of contact - if possible!

**Comment by nlordell** [comment]
Sure! I'm not sure I have `cargo publish` permissions and @vkgnosis is on vacation 😢.

**Comment by nlordell** [comment]
Just to set expectations - the release will likely only be possible in January once @vkgnosis is back from vacation. Maybe you have contact with other crate owners that can do the crates.io release for us?

**Comment by nlordell** [comment]
Created a PR to bump Cargo versions so that once we have someone with release access they can just `cargo publish`: https://github.com/rust-ethereum/ethabi/pull/253.

**Comment by gakonst** [comment]
@ordian maybe you are around and could help us out with the above?

**Comment by ordian** [comment]
@gakonst I have published v16.0.0 from the current master for ethabi, ethabi-derive, ethabi-contract, ethabi-cli.
Added `cargo owner --add nlordell` for ethabi, but for other packages I'm not able to.

**Comment by gakonst** [comment]
THANK YOU. Appreciate the quick turnaround.

**Comment by elpiel** [comment]
Hello,
Is it possible to also add a Changelog for `0.16`?
